###########################################################
#
# Simple Makefile for Operating Systems Project 1
# project1
#
###########################################################
.SUFFIXES: .h .c .cpp .l .o

project1: part-a part-b part-c

part-a: osproj2a.c
	gcc osproj2a.c -o osproj2a

part-b: osproj2b.c
	gcc osproj2b.c -o osproj2b

part-c: osproj2c.c
	gcc osproj2c.c -o osproj2c

#project1.o: compute_pi_montecarlo.c
#g++ -c project1.cpp

#project1.yy.o: project1.yy.c
#gcc -c project1.yy.c

#project1.yy.c: project1.l
#flex -oproject1.yy.c project1.l

clean:
	/bin/rm osproj2a osproj2b osproj2c 
