###########################################################
#
# Simple Makefile for Operating Systems Project 1
# project1
#
###########################################################
.SUFFIXES: .h .c .cpp .l .o

main: banker.cpp
	g++ banker.cpp -o banker

clean:
	/bin/rm banker
