#Christopher Carlisle
###########################################################
#
# Simple Makefile for Operating Systems Project 3
#
###########################################################
.SUFFIXES: .h .c .cpp .l .o

main: main.cpp buffer.h stats.h
	g++ main.cpp -o osproj -lpthread 

clean:
	/bin/rm osproj
