primethread_carlisle: primethread_carlisle.c
	gcc primethread_carlisle.c -lpthread -o primethread_carlisle

clean:
	/bin/rm primethread_carlisle

debug:
	gcc primethread_carlisle.c -lpthread -o primethread_carlisle -Wall
