#Christopher Carlisle
###########################################################
#
# Simple Makefile for Operating Systems Project 3
#
###########################################################
.SUFFIXES: .h .c .cpp .l .o

main: main.c buffer.h stats.h
	gcc main.c -o osproj -lpthread 

clean:
	/bin/rm osproj
